<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AntdUI.EmojiFluentFlat\AntdUI.EmojiFluentFlat.csproj" />
    <ProjectReference Include="..\..\src\AntdUI\AntdUI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Majorsilence.Forms/src/Majorsilence.Forms/Majorsilence.Forms.csproj" />
    <ProjectReference Include="../../../Majorsilence.Forms/src/Majorsilence.Forms.Avalonia/Majorsilence.Forms.Avalonia.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.CodeDom" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Majorsilence.Forms" />
    <Using Include="Majorsilence.Forms.Drawing" />
    <Using Include="System.Drawing" />
  </ItemGroup>
</Project>